// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		//receiving the input and declaring the variables
		int rounds = Integer.parseInt(args[0]);
		int posCounter = 0;
		int negCounter = 0;
		double rand = 0;
		double ratio = 0;
		int i = 0;

		//generating X random numbers and counting how many of them
		//are greater than 0.5 and how many are smaller or equal to 0.5
		while(i < rounds){
			rand = Math.random();
			if(rand > 0.5) posCounter ++;
			else negCounter++;
			i++;
		}
		//printing the results of the count
		System.out.println("> 0.5:  " + posCounter + " times");
		System.out.println("<= 0.5: " + negCounter + " times");

		//calculating the ratio between the results and printing it,
		//while making sure that we are not dividing by 0
		if((posCounter != 0) && (negCounter != 0)){
			if(posCounter < negCounter) ratio = (double)posCounter / (double)negCounter;
			else ratio = (double)negCounter / (double)posCounter;
			System.out.println("Ratio:  " + ratio);
		}
	}
}
